name: Release

on:
  push:
    # version tags are protected in this repository
    tags:
      - "v*"

permissions:
  contents: write

jobs:
  goreleaser:
    # use an environment when releasing
    environment: Publish

    runs-on: ubuntu-latest
    steps:

      - name: Checkout
        uses: actions/checkout@v4
        with:
          # history is required to enable release notes generation
          fetch-depth: 0

      - name: Configure Go
        uses: actions/setup-go@v5
        with:
          go-version-file: go.mod

      - name: Release
        uses: goreleaser/goreleaser-action@v6
        with:
          distribution: goreleaser
          version: v2.1.0
          args: release --clean
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
